version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
  backend:
    image: backend
    container_name: backend
    ports:
      - 8080:8080
    links:
      - mongodb
  frontend:
    image: frontend
    container_name: frontend
    ports:
      - 3000:3000
    links:
      - backend